spring:
  profiles:
    active: ${MY_ACTIVE_ENV:testing}
---
spring:
  profiles: testing
  data: 
    mongodb:
      uri: 'mongodb+srv://responsibilities:${MONGODB_PASSWORD_RESPONSIBILITIES}@nationwide-ld1bk.azure.mongodb.net/nationwide'

server:
  port: ${RESPONSIBILITIES_PORT}

---
spring:
  profiles: development
  data: 
    mongodb:
      uri: 'mongodb+srv://responsibilities:${MONGODB_PASSWORD_RESPONSIBILITIES}@nationwide-ld1bk.azure.mongodb.net/nationwide'

server:
  port: ${RESPONSIBILITIES_PORT}
---
spring:
  profiles: staging
  data: 
    mongodb:
      uri: 'mongodb+srv://responsibilities:${MONGODB_PASSWORD_RESPONSIBILITIES}@nationwide-ld1bk.azure.mongodb.net/nationwide'

server:
  port: ${RESPONSIBILITIES_PORT}
---
spring:
  profiles: production
  data:
    mongodb:
      uri: 'mongodb+srv://responsibilities:${MONGODB_PASSWORD_RESPONSIBILITIES}@nationwide-ld1bk.azure.mongodb.net/nationwide'

server:
  port: ${RESPONSIBILITIES_PORT}
